- .github/workflows/codeql.yml
Setting up code scanning. This change is auto-gen by GitHub.
> Setup CodeQL analysis

- .npmrc
- package.json
- pnpm-lock.yaml
- src/App.test.tsx
- src/App.tsx
- src/main.tsx
Integration of Cloudscape following https://cloudscape.design/get-started/integration/using-cloudscape-components/. Their demo component was replicated and tested to ensure we can render the components.
> add cloudscape

- .github/workflows/codeql.yml
One line change to specify the language for CodeQL to analyze and fix the workflow.
> fix codeql workflow

- README.md
- docs/architecture/architecture.md
- docs/architecture/decisions/template.md
- src/services/logger/Logger.test.ts
- src/services/logger/LoggerFactory.ts
- src/services/logger/index.ts
Changes include:
- Updated project README.md
- Added architectural decision record template (template.md) to new directory /docs/architecture/decisions/
- Added overall architecture document (architecture.md) to new directory /docs/architecture/
- Added Logger Mermaid diagram to overall architecture doc.
- Refactored LoggerFactory
> intitial documentation setup

- apps/core/package.json
- apps/core/src/main.ts
- pnpm-lock.yaml
Setup of automatic validation and transformation of incoming data on all endpoints of the NestJS app.
See the doc comment in `main.ts` for more info.
> setup global validation and transformation of incoming data

- .gitignore
- apps/core/package.json
- apps/core/src/repl.ts
Setup of NestJS REPL as development utility. Kinda of like a shell for the kernel! 
> setup core repl

- apps/core/package.json
- apps/core/src/main.ts
- apps/core/webpack-hmr.config.js
- pnpm-lock.yaml
Enable webpack hot-module replacement using NestJS recipe.
- [N/A] I have added tests that prove my fix is effective or that my feature works
> enable HMR on Core dev environment

- .github/workflows/build-test.yml
Adding GitHub action to ensure the application continues to build and the tests continue to pass.
> add build and test GitHub action to be run on PRs and pushes

- README.md
- apps/client/aws-resources.js
- apps/client/index.html
- apps/client/package.json
- apps/client/src/App.tsx
- apps/client/src/main.tsx
- apps/client/vite.config.js
- aws-resources-cfn-template.yaml
- pnpm-lock.yaml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
> feat: added Cognito user sign in to client

- apps/client/package.json
- apps/client/src/index.tsx
- apps/client/src/pages/Dashboard.tsx
- apps/client/src/pages/Login.tsx
- apps/client/src/styles/dashboard.css
- apps/client/src/styles/index.css
- packages/tsconfig/base.json
- yarn.lock
Introduced @iot-app-it/dashboard to dashboard page. Adds lint:fix command and removes duplicated ts rule.
Outstanding issues I plan to tackle in upcoming PRs:
- Styling issue. The data streams are rendering outside the chart.
- Need to backfill with e2e tests
> feat: add @iot-app-kit/dashboard to dashboard page

- README.md
- apps/core/api-resource-table-properties.js
- apps/core/jest-dynamodb-config.js
- apps/core/package.json
- apps/core/src/app.module.ts
- apps/core/src/config/database.config.ts
- apps/core/src/dashboards/dashboards.module.ts
- apps/core/src/dashboards/dashboards.service.ts
- apps/core/src/lifecycle-hooks/dynamodb-local-setup.ts
- aws-resources-cfn-template.yaml
Using the [`OnApplicationBootstrap` lifecycle hook](https://docs.nestjs.com/fundamentals/lifecycle-events) to launch a DynamoDB local instance for development environment.
> fix: launch DynamoDB local instance for development automatically

- apps/core/.cognito/README.md
- apps/core/.cognito/config.json
- apps/core/.cognito/db/clients.json
- apps/core/.cognito/db/us-west-2_h23TJjQR9.json
- apps/core/jest.config.ts
- apps/core/package.json
- apps/core/src/app.module.ts
- apps/core/src/auth/cognito-jwt-auth.guard.spec.ts
- apps/core/src/auth/cognito-jwt-auth.guard.ts
- apps/core/src/config/auth.config.ts
- apps/core/src/config/database.config.spec.ts
- apps/core/src/config/database.config.ts
- apps/core/src/config/local-cognito-jwt-verifier.ts
- apps/core/src/dashboards/dashboards.e2e.spec.ts
- apps/core/src/lifecycle-hooks/dynamodb-local-setup.ts
- turbo.json
Added cognito auth guard globally (including Dashboard APIs).
Other minor changes
- updated [database.config.ts](https://github.com/awslabs/iot-application/compare/main...chejimmy:iot-application:nest-auth?expand=1#diff-44af6d9e6def3bc3888b3a14cde2b7b142913ffd90a42a288f86621753087a42) to consume environment variables
- added [cognito-local](https://www.npmjs.com/package/cognito-local) and static resources configurations for local development purpose
> feat: added cognito auth guard globally

- .github/workflows/build-test.yml
-------
Fix broken syntax in build test github action.
> fix: built and test github action

- packages/jest-config/base.ts
- packages/lib/.eslintrc.js
- packages/lib/jest.config.ts
- packages/lib/package.json
- packages/lib/src/http/http.service.spec.ts
- packages/lib/src/http/http.service.ts
- packages/lib/src/http/http.types.ts
- packages/lib/src/http/index.ts
- packages/lib/src/index.ts
- packages/lib/tsconfig.json
- yarn.lock
Initial HTTP client library. In a follow-up PR, the client will be configured to append the bearer auth token header to outgoing requests to `core`.
> feat: http lib

- apps/core/package.json
- apps/core/src/app.module.ts
- apps/core/src/bootstrap/docs.bootstrap.ts
- apps/core/src/bootstrap/hmr.bootstrap.ts
- apps/core/src/bootstrap/index.ts
- apps/core/src/bootstrap/security.bootstrap.ts
- apps/core/src/bootstrap/server.bootstrap.ts
- apps/core/src/bootstrap/validation.bootstrap.ts
- apps/core/src/main.ts
- yarn.lock
Basic web security setup. Will tweak and improve iteratively.
> core security

- README.md
Doc update: added service dependencies info per environment
> chore: added service dependencies info per environment

- apps/client/src/breadcrumbs/breadcrumbs.spec.tsx
- apps/client/src/breadcrumbs/breadcrumbs.tsx
- apps/client/src/breadcrumbs/crumbs.hook.ts
- apps/client/src/breadcrumbs/page-crumb.type.ts
- apps/client/src/dashboard-list/dashboard-list.page-crumbs.ts
- apps/client/src/dashboard-list/dashboard-list.page.spec.tsx
- apps/client/src/dashboard/dashboard.page-crumbs.ts
- apps/client/src/func/last.ts
- apps/client/src/login/login.page-crumbs.ts
- apps/client/src/page/page-location.hook.ts
- apps/client/src/page/page-type.hook.ts
- apps/client/src/page/page.spec.tsx
- apps/client/src/page/page.tsx
- apps/client/src/root/root.page-crumbs.ts
- apps/client/src/root/root.tsx
- apps/client/src/router/route-match.type.ts
- apps/client/src/router/route-matches.hook.ts
- apps/client/src/router/routes.tsx
- apps/client/src/types/non-empty-list.ts
- tests/breadcrumbs.spec.ts
This change adds breadcrumbs to the application, utilizing Cloudscape `<BreadcrumbGroup />` and React Router.
> feat: breadcrumbs

- .dockerignore
- Dockerfile
- apps/core/package.json
- apps/core/src/bootstrap/server.bootstrap.ts
- apps/core/src/lifecycle-hooks/dynamodb-local-setup.ts
Added `Dockerfile` and `.dockerignore` to dockerize core service for cloud env
Optimized build size (227.06 MB; of which 176.75 MB of node image) and time (150.3s total; of which 95.2s of yarn install)
> feat: dockerizing core service for cloud env

- .github/workflows/playwright-test.yml
- playwright.config.ts
This change enables running `playwright` tests as a GitHub action.
Additionally, the `playwright.config.ts` includes an update to start the development server before running tests.
> feat: playwright github action

- .gitignore
- apps/client/src/index.tsx
- apps/client/src/layout/components/breadcrumbs/hooks/use-crumbs.ts
- apps/client/src/layout/components/top-navigation/top-navigation.tsx
- apps/client/src/routes/dashboards/dashboard.tsx
- apps/client/src/routes/dashboards/index.tsx
- apps/client/src/services/index.ts
- playwright.config.ts
- tests/auth.setup.ts
- tests/navigation.spec.ts
This change completes application authentication. It includes:
- Integration of Amplify `<Authenticator />`
- `getToken` method to call `core` APIs with the JWT (it also handles refresh of tokens)
- Removal of `react-router` loaders. Loaders are called outside of the context of rendering and appears incompatible for Amplify (loader is called before mounting Amplify and fails).
- Playwright test authentication.
> feat login

- README.md
- cdk/lib/asset/asset-bucket-stack.ts
- cdk/lib/asset/public-asset-stack.ts
- cdk/lib/core/core-service.ts
- cdk/lib/iot-application-stack.ts
Added Asset deployment via CDK. After the deployment, Client can login with Cognito user pool. However, the integration between Client and Core is not yet complete and further work is needed.
Key callouts:
- All public assets are deployed to a new folder for each deployment. This design prevents overwriting current assets and eliminates the incompatibility between assets.
- CloudFront distribution is updated to point to the new folder after the assets deployment.
> feat: Asset cdk deployment

- apps/client/package.json
- apps/core/package.json
- yarn.lock
Routine upgrade which resolves 2 dependabot issues.
> chore: upgrade nanoid

- apps/client/src/routes/dashboards/create/create-dashboard-page.tsx
Small refactor to use `isNotFatal` utility.
> refactor: use isNotFatal for create dashboard form

- apps/client/package.json
- apps/client/src/routes/dashboards/create/create-dashboard-page.tsx
- apps/client/src/routes/dashboards/dashboards-index/components/delete-dashboard-modal.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
- yarn.lock
This change adds the `react-hook-form` devtool to the client and integrates the tool into all 3 of the application forms.
Note: Indentation changes made the diff large, while only a few lines we added to each form's containing component.
The change resolves https://github.com/awslabs/iot-application/issues/87.
> feat: add react-hook-form devtools

- .github/workflows/diagram.yml
- README.md
The change adds a project visualization to our `README.md`, created automatically through a GitHub action. See https://githubnext.com/projects/repo-visualization/ for more information.
> docs: add project visualization

- .github/workflows/diagram.yml
- README.md
Follow up to https://github.com/awslabs/iot-application/pull/139 to add a project visualization to the repo.
It didn't work! Trying again! :)
> fix: project viz

- apps/client/package.json
- apps/client/src/index.tsx
- apps/client/src/metrics/metric-handler.spec.ts
- apps/client/src/metrics/metric-handler.ts
- yarn.lock
Add the capability to capture and batch web-vitals. Currently logging to the console but in the future we will POST to an `/analytics` endpoint.
Fixes https://github.com/awslabs/iot-application/issues/97
> feat: capture web vitals

- cdk/lib/asset/public-asset-stack.ts
Latest SSL recommendation to use security policy TLSv1.2_2021
Config update only
> fix: CloudFront distribution min SSL version of TLSv1.2_2021

- apps/client/src/routes/dashboards/dashboard/dashboard-page.tsx
Replaced hardcoded AWS credentials with Cognito credentials for Dashboard.
> feat: Dashboard to use Cognito creds

- apps/client/package.json
- apps/client/src/routes/dashboards/dashboard/dashboard-page.tsx
- yarn.lock
chore: upgrade @iot-app-kit/dashboard to 5.5.0
Upgrade only; all existing test passed
> chore: upgrade @iot-app-kit/dashboard to 5.5.0

- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
Display date string in locale format.
> feat(client): display date in a more readable format

- aws-resources-cfn-template.yaml
Updated the `aws-resources-cfn-template.yaml` to deploy with prebuild artifact
> feat: CloudFormation deployment with prebuild artifact

- apps/core/package.json
- yarn.lock
This change upgrades cognito-local to the latest version.
> chore: update cognito-local from 3.21.1 to 3.23.1

- apps/client/package.json
- package.json
- packages/tsconfig/base.json
- yarn.lock
> chore: upgrade to typescript 5

- aws-resources-cfn-template.yaml
- cdk/lib/asset/public-asset-stack.ts
- cdk/lib/csp/public-asset-directives.ts
- cdk/lib/endpoints/aws-endpoints.ts
- cdk/lib/iot-application-stack.ts
Added essential CSP directives to public asset distribution to help mitigate many common web attacks, mostly related to cross-site scripting (XSS).
> fix: added essential CSP directives to public asset distribution

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/dependabot-hook.yml
- .github/workflows/diagram.yml
- .github/workflows/lint.yml
- .github/workflows/playwright.yml
- .github/workflows/test.yml
Revise and decompose CI workflows to increase rate of development. All workflows are capped at 10 minutes, meaning all PRs should be validated in under 10 minutes.
> ci: workflow

- aws-resources-cfn-template.yaml
Disabled UserPool signup to prevent unwanted sign-up
> fix: disabled UserPool signup in CloudFormation template

- README.md
The change revises and expands the README overview for the repo, making it clear to customers what they are getting.
> docs: improve README overview

- .github/workflows/deployment.yml
GitHub workflow to deploy CDK on PR and push to main. Not required for PR at this moment.
Further speed and timeout tuning needed. This PR will help us get more info and metrics into deployment to tune it 🔧
> chore: github workflow to deploy CDK on PR and push to main

- apps/client/src/data/query-client.spec.tsx
- apps/client/src/data/query-client.ts
This change signs out users when a 401 Unauthorized request is sent from Core.
> feat: sign out unauthenticated users

- cdk/lib/iot-application-stack.ts
- cdk/package.json
- fixed lints in cdk
- added script to fix lint in cdk
Lint passing; No more lint;
> fix: cdk lint

- package.json
This change adds two install scripts to reduce repetitive behavior.
> chore: add install:clean and install:reset scripts

- tests/dashboards/dashboard-management.spec.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
> chore: fixed dashboard time range selection under e2e test

- .github/workflows/distribution.yml
- cfn-template.json
This PR adds auto update to the application. By adding a CodePipeline resource to the `cfn-template.json`, it allows for auto update to the application CloudFormation stack. The CodePipeline includes stages:
1. S3 source to track (poll) for distribution update
2. Deploy action to deploy updated `cfn-template.json` to CloudFormation
Other changes:
- marked all resources to have a dependency on "CloudFormationRole" (`"DependsOn": [ "CloudFormationRole" ]`) to serialize the creation, update, and deletion orders; this is necessary to ensure the CloudFormation stack has the required permission to perform the executions - [1] CloudFormationRole is created/updated before other resources; [2] other resources are deleted before CloudFormationRole
- renamed the CFN template zip file to …
> chore: added CodePipeline to cfn-template for auto update

- apps/client/package.json
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.spec.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
- apps/client/src/routes/dashboards/dashboards-index/hooks/use-table-preferences.ts
- apps/client/src/routes/dashboards/dashboards-index/styles.css
- apps/client/src/styles/variables.css
- apps/core/.cognito/db/us-west-2_h23TJjQR9.json
- package.json
- playwright.config.ts
- playwright/.auth/user.json
- yarn.lock
this is a replication of https://github.com/awslabs/iot-application/pull/1109. The original CR has the e2e tests failing, there are no apparent reason, but i have updated the playwright test version,
> feat: update dashboard table

- .github/workflows/deployment.yml
The deploy step is failing to get crendentials
> fix for deploy action failures

- .github/workflows/deployment-pr.yml
- README.md
- cdk/bin/cdk.ts
- cdk/cdk.json
PR and main push triggers deployment to the same environment and the changes override each other.
The PR isolates deployment environments by PR and push to main.
See `Deployment PR` workflow triggered by this PR
> chore: isolate deployment environments by PR and push to main

- cdk/bin/cdk.ts
Fixed lint introduced by this PR: https://github.com/awslabs/iot-application/actions/runs/6113031331/job/16591687515
Lint passed locally
> chore: cdk lint fix

- apps/client/src/layout/components/footer/footer.css
- apps/client/src/layout/components/footer/footer.spec.tsx
- apps/client/src/layout/components/footer/footer.tsx
- apps/client/src/layout/components/footer/index.ts
- apps/client/src/layout/layout.tsx
Adding custom footer throughout with static content.
Please note: For now, we removed empty links as discussed.
> [UX] Add footer throughout #949

- apps/client/src/routes/dashboards/create/components/create-dashboard-form-actions.tsx
- apps/client/src/routes/dashboards/create/components/dashboard-description-field.tsx
- apps/client/src/routes/dashboards/create/components/dashboard-name-field.tsx
- apps/client/src/routes/dashboards/create/create-dashboard-page.tsx
- tests/pages/create-dashboard.page.ts
This PR is for the create dashboard workflow updates. new changes include
1. Removed "General Details" header text
2. Changed "Create dashboard" button to just "Create"
3. Changed "Dashboard name" to just "Name"
4. Changed "Dashboard description" to just "description", and removed optional text
5. Moved "Create a dashboard to monitor your assets and properties." text to under the "Create dashboard" header text
> feat: updated copy on dashboard creation workflow

- userguide/README.md
Edited README in a new branch for for writer of IoT Application feature. Also in Slack, I informed the writer that feature names are usually lowercase. Which means the feature name would be  "IoT application" unless the team files a ticket and the naming manager approves the capital A. I gave the writer the SIM link to request the name.
No tests. Changes based on established Style Guide rules and offering names rules.
> Edits to README.md

- apps/client/package.json
- yarn.lock
Update to latest version of iot-app-kit/dashboard
> chore(deps): bump @iot-app-kit/dashboard to 8.1.1

- cdk/lib/auth/auth-stack.ts
- cdk/lib/csp/public-asset-directives.ts
- cdk/lib/endpoints/aws-endpoints.ts
This PR fixes the problem where browser is blocking connections to TwinMaker endpoints, hence, blocking the all TwinMaker requests.
> fix: added TwinMaker endpoints under CSP

- apps/client/src/routes/dashboards/dashboards-index/components/getting-started.spec.tsx
- apps/client/src/routes/dashboards/dashboards-index/components/getting-started.tsx
Issue: https://github.com/awslabs/iot-application/issues/1346
Description: Homepage: Update getting started copy
Changes done in the CR:
-Updated copy for the getting started sections 3 steps.
-Wrote test cases to check the updated text.
> feat: updated copy for the getting started sections 3 sections

- .github/workflows/lint.yml
- .github/workflows/test.yml
Lint and test actions were not setup to run on PRs. This change resolves this issue.
> fix: run lint and test on PR

- README.md
- deploymentguide/README.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
> fix: update README to provide better setup instructions

- .github/workflows/deployment-pr.yml
PR deployment hook was accidentally removed. Adding it back.
> fix: add back deployment PR hook

- apps/client/package.json
- yarn.lock
Update @iot-app-kit/dashboard@9.0.0
Manually tested all commits within the release delta
> chore(deps): update @iot-app-kit/dashboard to 9.0.0

- apps/client/package.json
- yarn.lock
Release changes documented here: https://github.com/awslabs/iot-app-kit/pull/2098
This change does not introduce any new API calls, or modify any APIs of IoT App Kit dashboard.
Manually verified every commit
> chore(deps): update to @iot-app-kit/dashboard@9.1.0

- apps/client/package.json
- yarn.lock
releases changes contained within https://github.com/awslabs/iot-app-kit/pull/2101#pullrequestreview-1683394253
Manually tested changes in https://github.com/awslabs/iot-app-kit/pull/2101#pullrequestreview-1683394253
> chore(deps): update to @iot-app-kit/dashboard@9.2.0

- apps/client/package.json
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
- apps/client/src/routes/dashboards/dashboards-index/styles.css
- yarn.lock
merges in release candidate branch
> chore: merge in rc

- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
updated the WCAG compliance for dashboard table selection checkbox
> feat: updated the wcag compliance for dashboard table selection checkbox

- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
updated the WCAG compliance for dashboard pagination buttons
> feat: updated wcag compliance for dashboard pagination buttons

- apps/core/src/dashboards/dashboards.e2e.spec.ts
Validate that the system denies connections from an unauthenticated caller.
> chore: added Dashboard APIs unauthenticated test cases

- apps/core/src/auth/cognito-jwt-auth.guard.ts
A service log should be able to answer questions such as “who did what when?” without including sensitive information such as passwords or secrets.
sample log: `LOG [CognitoJwtAuthGuard] User ID "c443af37-2eab-4465-ac94-7ec8b814abad" authorized to DashboardsController.read (url: "/api/dashboards/M8Dsr97LK0fC")`
> chore: added secure logging

- apps/core/src/app.module.ts
- apps/core/src/migration/README.md
- apps/core/src/migration/migration.controller.ts
- apps/core/src/migration/migration.e2e.spec.ts
- apps/core/src/migration/migration.module.ts
- apps/core/src/migration/migration.service.ts
* Adding basic NestJS endpoint for /migration
* Right now it accepts requests and returns success without any processing
* I will be expanding this API to handle status updates and perform the SiteWise Monitor to Centurion dashboard migration
> feat: add basic migration API

- apps/client/src/helpers/featureFlag/featureFlag.spec.ts
- apps/client/src/helpers/featureFlag/featureFlag.ts
- apps/client/src/routes/dashboards/dashboards-index/components/migration.spec.tsx
- apps/client/src/routes/dashboards/dashboards-index/components/migration.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
- apps/client/src/services/generated/index.ts
- apps/client/src/services/generated/services/MigrationService.ts
- apps/client/src/services/index.ts
- apps/core/src/dashboards/entities/dashboard.entity.ts
* Adding a basic UX, hidden under a flag, which calls the Migration API
* Add generated service from the migration API
* Remaining followups: Updating UX based on status, polling the migration API for status, 
> feat: add basic dashboard migration UX and generated service

- apps/client/package.json
- yarn.lock
This is a dependency update of @iot-app-kit/dashboard@9.4.0
> Dashboard 9.4.0

- Dockerfile
fixed docker client build by allocating Node memory to 4GB
Passing workflow https://github.com/awslabs/iot-application/actions/runs/6670888720/job/18131847743?pr=1604
> Fix docker client build

- apps/core/src/bootstrap/security.bootstrap.e2e.spec.ts
Added test cases for security CSP and headers.
> chore: security bootstrap tests

- tests/functional-homepage-iot-application/add-footer-throughout.spec.ts
- tests/pages/application-frame.page.ts
Issue : https://github.com/awslabs/iot-application/issues/949
Description : 
Created Functional testing for the Footer covering positive and negative scenarios.
> Added footer functional testing #949

- cdk/lib/core/core-service.ts
Configured the Core service to align with target usage pattern
- 1 vCPU with 2 GB Memory
- 1 stance without scaling
Other configurations would be handled as feature requests
[Successful deployment](https://github.com/awslabs/iot-application/actions/runs/6795214643/job/18472909067?pr=1680)
Previously load tested 🏋️‍♀️
> chore: Core service instance and scaling configurations

- apps/client/package.json
- apps/client/src/auth/auth-service.interface.ts
- apps/client/src/auth/auth-service.ts
- apps/client/src/metrics/cloud-watch-metrics-recorder.spec.ts
- apps/client/src/metrics/cloud-watch-metrics-recorder.ts
- apps/client/src/metrics/metrics-recorder.interface.ts
- apps/client/src/routes/dashboards/dashboard/dashboard-page.tsx
- apps/client/src/services/index.ts
- apps/client/src/test/setup.ts
- apps/core/package.json
- yarn.lock
- [chore: update @aws-sdk/* to 3.450.0](https://github.com/awslabs/iot-application/pull/1757/commits/a6a16722b0515c728b9e905fc7d7e9cb096ba8a1)
- update @aws-sdk/* to the latest version that's compatible with `aws-sdk-client-mock`; related https://github.com/m-radzikowski/aws-sdk-client-mock/issues/193
- [feat: cloudwatch metrics recorder implementation](https://github.com/awslabs/iot-application/pull/1757/commits/06a23edb415fc50d44973d0964ba3b0b7779597f)
- added CloudWatch metrics recorder implementation
- `metrics-recorder.interface.ts` is copied from [app-kit](https://github.com/awslabs/iot-app-kit/blob/rc/packages/core/src/metric-recorder/metricsRecorder.interface.ts) to unblock implementation until a new version includes the interface is released
- Next action item(s)
- User …
> Feat CloudWatch metrics recorder

- cdk/lib/core/core-service.ts
* Add a policy to the core service that gives permission for the SiteWise List APIs and DescribeDashboard. These API calls are required for dashboard migration.
> feat: migration permission update

- apps/client/src/routes/dashboards/create/components/dashboard-description-field.tsx
- apps/client/src/routes/dashboards/create/components/dashboard-name-field.tsx
Updates the constraint text of the create dashboard form fields.
> fix: update create dashboard form constraint text

- apps/client/package.json
- yarn.lock
chore: upgrade dashboard to 9.8.0 #1786
> chore: upgrade dashboard to 9.8.0

- apps/client/src/initialize-auth-dependents.tsx
- apps/client/src/logging/cloud-watch-logger.ts
Small update as follow up to https://github.com/awslabs/iot-application/pull/1788
> Chore init code styles

- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
Header section: updated some aria labels and added a missing one for the clear filter SVG button
used a screen reader
> fix: update aria labels

- apps/client/src/layout/layout.tsx
Issue: #1800 
Added condition to remove breadcrumb in iot app kit dashboard page.
https://github.com/awslabs/iot-application/assets/139960352/aa88eb0b-b246-496f-b3f3-f5db965ab1eb
> feat: remove breadcrumb in iot appkit dashboard page

- apps/client/package.json
- yarn.lock
Dependency update to latest version of @iot-app-kit/dashboard, 9.9.0
> chore(deps): update @iot-app-kit/dashboard to 9.9.0

- apps/client/package.json
- yarn.lock
update to @iot-app-kit/dashboard@9.9.1
> chore(deps): update to @iot-app-kit/dashboard@9.9.1

- apps/client/package.json
- yarn.lock
update to @iot-app-kit/dashboard@9.10.0
No new APIs are introduced in the change.
> chore(deps): update to @iot-app-kit/dashboard@9.10.0

- apps/client/src/helpers/featureFlag/featureFlag.spec.ts
- apps/client/src/helpers/featureFlag/featureFlag.ts
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.spec.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
* This change removes the migration feature flag and will release it
> feat: remove feature flag, release migration

- userguide/README.md
* Add migration instructions to the user guide
> feat: add migration instructions/limitations to userguide

- apps/client/package.json
- apps/core/package.json
- cdk/package.json
- deploymentguide/README.md
- package.json
- packages/eslint-config-custom/package.json
- turbo.json
* Add a deploy command which ensures dependencies are installed, workspace is clean 
* Removed the `rmraf node_modules` since clean should just delete the build folders
> feat: add deploy command to simplify deployment

- apps/client/config-overrides.js
- apps/client/src/index.tsx
- apps/client/src/register-loggers.ts
- apps/client/src/register-metrics-recorder.ts
- apps/client/src/routes/dashboards/dashboards-index/components/migration.spec.tsx
- apps/client/src/routes/dashboards/dashboards-index/components/migration.tsx
- apps/client/src/services/generated/models/MigrationStatus.ts
- apps/client/src/structures/notifications/info-notification.spec.ts
- apps/client/src/structures/notifications/info-notification.ts
- apps/core/src/migration/entities/migration-status.entity.ts
- apps/core/src/migration/migration.e2e.spec.ts
- apps/core/src/migration/service/migration.service.ts
PRs merged on 23/12/7 were missing in rc/main branch. This PR adds the missing PRs commits back.
- https://github.com/awslabs/iot-application/pull/1846
- https://github.com/awslabs/iot-application/pull/1847
> Fix missing merged commits

- apps/client/src/helpers/featureFlag/featureFlag.spec.ts
- apps/client/src/helpers/featureFlag/featureFlag.ts
- apps/client/src/routes/dashboards/dashboards-index/components/getting-started.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.spec.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
- userguide/README.md
* Adding missed commits back to rc branch
* Adding
* https://github.com/awslabs/iot-application/pull/1860
* https://github.com/awslabs/iot-application/pull/1862
* https://github.com/awslabs/iot-application/pull/1861
> Fix rc mcm

- apps/client/package.json
* Removing vite plugins that didn't end up being used
> Remove unused vite dependencies

- tests/dashboard-list-page.spec.ts
- tests/helpers.ts
- tests/pages/dashboards-index.page.ts
This change adds Playwright test fixtures to improve our ability to test the dashboard list page.
> feat: dashboard list page test fixtures

- apps/client/src/routes/dashboards/create/create-dashboard-page.tsx
- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
Issue : https://github.com/awslabs/iot-application/issues/1928
Fix:
Added a flag to check production env and conditionally rendered devtool.
> feat: react-hook-form devtools exposed in production #1928

- apps/client/src/routes/dashboards/dashboard/dashboard-page.tsx
- tests/dashboards/dashboard-management.spec.ts
This PR is for #1927
Fixes #1927
Removed dashboard name from dashboard definition prop and added it as a direct prop.
https://github.com/awslabs/iot-application/assets/139960352/dbd8fef3-773f-45f6-8d3d-1e14db8f25ae
> fix: dashboard name missing

- apps/client/src/routes/dashboards/dashboards-index/dashboards-index-page.tsx
- tests/dashboard-list-page.spec.ts
- tests/dashboard-list-page.spec.ts-snapshots/dashboard-list-page-accessibility-scan-results-chromium-darwin
- tests/dashboard-list-page.spec.ts-snapshots/dashboard-list-page-accessibility-scan-results-firefox-darwin
- tests/dashboard-list-page.spec.ts-snapshots/dashboard-list-page-accessibility-scan-results-webkit-darwin
* Adding the accessibility scan for dashboard list page
* Added `target-size` violation as expected since we have higher priority fixes to make first
> feat: add dashboard list accessbility tests

- apps/client/src/index.tsx
- apps/client/src/services/index.ts
- apps/client/src/services/local-storage-dashboard/dashboard-service.ts
- apps/client/src/services/types.ts
Added an local storage dashboard service for edge mode usage.
Unit tests added
> feat: edge mode dashboard service

- apps/client/src/auth/auth-service.interface.ts
- apps/client/src/auth/auth-service.ts
- apps/client/src/auth/edge-auth-service.ts
- apps/client/src/routes/dashboards/dashboard/dashboard-configuration.ts
- apps/client/src/routes/dashboards/dashboard/dashboard-page.tsx
- apps/client/src/routes/edge-login/edge-login-page.tsx
* Adding edgeEndpoint to authservice
* Passing the edge client config to app kit
* Credit to chejimmy@ for `dashboard-configuration.ts` since I mostly copied from his prototype
> feat: edge app kit client config

- apps/client/src/constants/format.ts
- apps/client/src/constants/index.ts
- apps/client/src/index.tsx
- apps/client/src/layout/components/top-navigation/top-navigation.tsx
- apps/client/src/routes/edge-login/edge-login-page.spec.tsx
- apps/client/src/routes/edge-login/edge-login-page.tsx
- apps/client/src/routes/edge-login/edge-login-route.tsx
- apps/client/src/routes/root-index/index.ts
- apps/client/src/routes/root-index/root-index-route.tsx
- apps/client/src/routes/root/root-route.tsx
* Adding logout support in edge mode which navigates back to login page and clears credentials 
> feat: support edge logout

- cdk/lib/core/core-service.ts
- cdk/lib/iot-application-stack.ts
- deployCdk.js
* Add edge as a deployment options. Adds input for edge gateway. Deployed application will query the edge gateway specified in deployment.
> feat: add edge as a deployment option

- apps/core/src/migration/service/convert-monitor-to-app-definition.ts
* Got feedback that migration was causing some style issues like not having the legend expanded on the migration charts. This is because we changed the dashboard definition legend configuration. This change updates the configuration to properly handle the legend.
> fix: update migration logic to match updated dashboard definition

- tests/dashboard-list-page.spec.ts
- tests/dashboards/dashboard-management.spec.ts
> chore: fix tests

- tests/dashboard-list-page.spec.ts
- tests/dashboards/dashboard-management.spec.ts
> chore: fix flaky tests

- README.md
- app-deployment-cfn.template.yaml
- deploymentguide/README.md
- developmentguide/README.md
Due to popular request, we are adding a CloudFormation template to allow customers to deploy the application without the need of setting up a deployment/development environment.
Manually validated in new account and various regions.
> chore: added a CloudFormation template to deploy the application

- README.md
Add a deprecation notice to properly communicate the repo deprecation for our external customers.
> feat: deprecation notice
